from database.connection import volunteers_collection

volunteers = [
    {
        "name": "Aman",
        "phone": "9876543210",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 31.9119,
        "longitude": 75.2673,
        "skills": ["Boat Rescue", "Medical"],
    },
    {
        "name": "Harman",
        "phone": "9865478943",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 31.9119,
        "longitude": 75.2673,
        "skills": ["Boat Rescue", "Medical"],
    },
    {
        "name": "Karman",
        "phone": "9865678921",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 31.9119,
        "longitude": 75.2673,
        "skills": ["Boat Rescue", "Medical"],
    },
    {
        "name": "Aman Singh",
        "phone": "9876500001",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 32.0416,
        "longitude": 75.4031,
        "skills": ["Boat Rescue", "Medical"],
    },
    {
        "name": "Harman Singh",
        "phone": "9876500002",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 32.0416,
        "longitude": 75.4031,
        "skills": ["Food Distribution"],
    },
    {
        "name": "Karanpreet Singh",
        "phone": "9876500003",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 32.0416,
        "longitude": 75.4031,
        "skills": ["Medical"],
    },
    {
        "name": "Simran Kaur",
        "phone": "9876500004",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 32.0416,
        "longitude": 75.4031,
        "skills": ["Boat Rescue"],
    },
    {
        "name": "Manpreet Kaur",
        "phone": "9876500005",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 32.0416,
        "longitude": 75.4031,
        "skills": ["Medical", "Food Distribution"],
    },
    {
        "name": "Jaspreet Singh",
        "phone": "9876500006",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 32.0416,
        "longitude": 75.4031,
        "skills": ["Rescue"],
    },
    {
        "name": "Gurleen Kaur",
        "phone": "9876500007",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 32.0416,
        "longitude": 75.4031,
        "skills": ["Medical"],
    },
    {
        "name": "Harjit Singh",
        "phone": "9876500008",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 32.0416,
        "longitude": 75.4031,
        "skills": ["Boat Rescue"],
    },
    {
        "name": "Navdeep Singh",
        "phone": "9876500009",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 32.0416,
        "longitude": 75.4031,
        "skills": ["Food Distribution"],
    },
    {
        "name": "Rupinder Kaur",
        "phone": "9876500010",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 32.0416,
        "longitude": 75.4031,
        "skills": ["Medical"],
    },
    {
        "name": "Sukhdeep Singh",
        "phone": "9876500011",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 32.0416,
        "longitude": 75.4031,
        "skills": ["Boat Rescue"],
    },
    {
        "name": "Lovepreet Singh",
        "phone": "9876500012",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 32.0416,
        "longitude": 75.4031,
        "skills": ["Medical"],
    },
    {
        "name": "Arshdeep Kaur",
        "phone": "9876500013",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 32.0416,
        "longitude": 75.4031,
        "skills": ["Food Distribution"],
    },
    {
        "name": "Param Singh",
        "phone": "9876500014",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 32.0416,
        "longitude": 75.4031,
        "skills": ["Boat Rescue"],
    },
    {
        "name": "Dilpreet Singh",
        "phone": "9876500015",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 32.0416,
        "longitude": 75.4031,
        "skills": ["Medical"],
    },
    {
        "name": "Rajveer Singh",
        "phone": "9876500016",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 32.0416,
        "longitude": 75.4031,
        "skills": ["Food Distribution"],
    },
    {
        "name": "Amandeep Kaur",
        "phone": "9876500017",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 32.0416,
        "longitude": 75.4031,
        "skills": ["Medical"],
    },
    {
        "name": "Jagmeet Singh",
        "phone": "9876500018",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 32.0416,
        "longitude": 75.4031,
        "skills": ["Boat Rescue"],
    },
    {
        "name": "Mandeep Singh",
        "phone": "9876500019",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 32.0416,
        "longitude": 75.4031,
        "skills": ["Food Distribution"],
    },
    {
        "name": "Preet Kaur",
        "phone": "9876500020",
        "location": "Gurdaspur",
        "available": True,
        "latitude": 32.0416,
        "longitude": 75.4031,
        "skills": ["Medical"],
    },
]


# Delete old volunteers
volunteers_collection.delete_many({})

# Insert new volunteers
volunteers_collection.insert_many(volunteers)

print("✅ Volunteers inserted successfully!")